### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by haltuf** [honzagula/sendgrid-nette#1]
Attachments cannot be sent in the current version of sendgrid-nette.

**Comment by honzagula** [comment]
Good point. I will try to integrate it ASAP

**Comment by honzagula** [comment]
Version 1.1.0 was released. Please update this package and edit your service in config to:
`nette.mailer: Istrix\Mail\SendgridMailer(%sendgrid.key%, %tempDir%)`

**Comment by haltuf** [comment]
Awesome! Thank you!
