### ISSUE TITLE
addCc, addBcc does not work

### ISSUE THREAD

**Issue by haltuf** [honzagula/sendgrid-nette#2]
If the cc and bcc is set in the Nette\Mail\Message, it is ignored and not delivered.

`$message->addTo('mail1');`
`$message->addCc('mail2');`
`$message->addBcc('mail3');`
`$this->mailer->send($message);`

Only mail1 receives the message.

**Comment by honzagula** [comment]
Thank you for reporting. Implemented to version 1.1.1. Please update your repository :)

**Comment by haltuf** [comment]
Thanks for such a fast solution!
